name: tennis
description: "Application de gestion de tournois de tennis"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.0.5
  intl: ^0.18.1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.13.0

flutter_native_splash:
  color: "#2a5799"  # Couleur de fond bleu
  image: assets/images/tennis_logo.png
  android: true
  ios: true
  web: true
  branding: assets/images/tennis_logo.png
  android_gravity: center
  ios_content_mode: center

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/tennis_logo.png"
  android_adaptive_icon_background: "#2a5799"
  ios_remove_alpha_icon: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/tennis_logo.png